default: &default
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  adapter: mysql2
  username: root
  password:
  host: localhost
  database: furima3_38129_development

test:
  <<: *default
  adapter: mysql2
  username: root
  password:
  host: localhost
  database: furima3_38129_test

production:
  <<: *default
  database: furima3_38129_production
  username: furima3_38129
  password: <%= ENV['FURIMA3_38129_DATABASE_PASSWORD'] %>